proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  container-wait-time: 60000
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  specs:
    - id: filebrowser
      displayName: File Browser
      containerImage: filebrowser
      port: 80
      container-volumes: [ "/tmp/filebrowser-demo:/mnt" ]
      container-env:
        ROOT_PATH: "/mnt"
        PUID: "1000"
        PGID: "1000"
logging:
  file:
    name: shinyproxy.log
